// Generated by 'unplugin-auto-import'
export {};
declare global {
  const useCallback: typeof import("preact/hooks")["useCallback"];
  const useContext: typeof import("preact/hooks")["useContext"];
  const useEffect: typeof import("preact/hooks")["useEffect"];
  const useMemo: typeof import("preact/hooks")["useMemo"];
  const useReducer: typeof import("preact/hooks")["useReducer"];
  const useRef: typeof import("preact/hooks")["useRef"];
  const useState: typeof import("preact/hooks")["useState"];
}
